# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Build Puppetstring Model Viewer

on: workflow_dispatch

permissions:
  contents: write

jobs:
  linux-build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - uses: dlang-community/setup-dlang@v1.4.0
      with:
        compiler: ldc-latest
  
    - name: 'Preparing build... (Ubuntu)'
      run: |
        sudo apt install libsdl2-dev libfreetype6-dev
      
    - name: 'Clone dependencies & set versions'
      run: |
        git clone https://github.com/Inochi2D/i2d-imgui.git --recurse-submodules
        git clone https://github.com/Inochi2D/dcv-i2d
        dub add-local i2d-imgui/ "0.8.0"
        dub add-local dcv-i2d/ "0.3.0"

    - name: 'Update version info'
      run: |
        # Build metadata (like version information and icons)
        dub build --config=update-version

    - name: 'Build Inochi Session'
      run: |
        # Build metadata (like version information and icons)
        dub build --config=meta

        # Build the project, with its main file included, without unittests
        dub build --compiler=ldc2 --build=release --config=linux-full

    - name: 'Archive ZIP'
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'puppetstring-modelviewer-linux-x86_64.zip'
        directory: 'out/'
        path: '*'

    - name: 'Release ZIP'
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: 'out/puppetstring-modelviewer-linux-x86_64.zip'

  windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dlang-community/setup-dlang@v1.4.0
      with:
        compiler: ldc-latest

    - name: 'Preparing build... (Windows)'
      run: |
        Remove-Item 'C:/Strawberry' -Recurse
        .\vcvars.ps1
      
    - name: 'Clone dependencies & set versions'
      run: |
        git clone https://github.com/Inochi2D/i2d-imgui.git --recurse-submodules
        git clone https://github.com/Inochi2D/dcv-i2d
        dub add-local i2d-imgui/ "0.8.0"
        dub add-local dcv-i2d/ "0.3.0"

    - name: 'Update version info'
      run: |
        # Build metadata (like version information and icons)
        dub build --config=update-version

    - name: 'Build Inochi Session'
      run: |
        # Build metadata (like version information and icons)
        dub build --config=meta
          
        # Build the project, with its main file included, without unittests
        dub build --compiler=ldc2 --build=release --config=win32-full
          
    - name: 'Archive ZIP'
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'puppetstring-modelviewer-win32-x86_64.zip'
        directory: 'out/'
        path: '*'

    - name: 'Release ZIP'
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: out/puppetstring-modelviewer-win32-x86_64.zip

  macOS-build:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    - uses: dlang-community/setup-dlang@v1.4.0
      with:
        compiler: ldc-latest

    - name: 'Preparing build... (macOS)'
      run: |
        export HOMEBREW_NO_INSTALL_CLEANUP=1
        export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1

        # Remove conflicting brew items
        brew remove --ignore-dependencies libpng brotli harfbuzz

        # Delete fake harfbuzz if need be
        if [ -f "/usr/local/lib/libharfbuzz.dylib" ]; then
          sudo rm -r /usr/local/lib/libharfbuzz.dylib
        fi

        # And the .a for it as well
        if [ -f "/usr/local/lib/libharfbuzz.a" ]; then
          sudo rm -r /usr/local/lib/libharfbuzz.a
        fi
      
    - name: "Clone dependencies & set versions"
      run: |
        git clone https://github.com/Inochi2D/i2d-imgui.git --recurse-submodules
        git clone https://github.com/Inochi2D/dcv-i2d
        dub add-local i2d-imgui/ "0.8.0"
        dub add-local dcv-i2d/ "0.3.0"

    - name: 'Update version info'
      run: |
        # Build metadata (like version information and icons)
        dub build --config=update-version

    - name: 'Build (OSX Universal)'
      run: |
        dub build --config=meta

        # First build ARM64 version...
        echo "Building arm64 binary..."
        dub build --build=release --compiler=ldc2 --config=osx-full --arch=arm64-apple-macos
        mv "out/Puppetstring Model Viewer.app/Contents/MacOS/puppetstring-modelviewer" "out/Puppetstring Model Viewer.app/Contents/MacOS/puppetstring-modelviewer-arm64"

        # Then the X86_64 version...
        echo "Building x86_64 binary..."
        dub build --build=release --compiler=ldc2 --config=osx-full --arch=x86_64-apple-macos
        mv "out/Puppetstring Model Viewer.app/Contents/MacOS/puppetstring-modelviewer" "out/Puppetstring Model Viewer.app/Contents/MacOS/puppetstring-modelviewer-x86_64"

        # Glue them together with lipo
        echo "Gluing them together..."
        lipo "out/Puppetstring Model Viewer.app/Contents/MacOS/puppetstring-modelviewer-x86_64" "out/Puppetstring Model Viewer.app/Contents/MacOS/puppetstring-modelviewer-arm64" -output "out/Puppetstring Model Viewer.app/Contents/MacOS/puppetstring-modelviewer" -create
        
        # Cleanup
        echo "Cleaning up..."
        rm "out/Puppetstring Model Viewer.app/Contents/MacOS/puppetstring-modelviewer-x86_64" "out/Puppetstring Model Viewer.app/Contents/MacOS/puppetstring-modelviewer-arm64"
        
        # Bundle
        echo "Bundling up to app"
        ./build-aux/osx/osxbundle.sh

    - name: Archive Zip
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'puppetstring-modelviewer-macOS.zip'
        directory: 'out/'
        path: '*'
